/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WebformColumn service. Represents a row in the &quot;RcsWebform_WebformColumn&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rcs.dbservice.model.impl.WebformColumnModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rcs.dbservice.model.impl.WebformColumnImpl}.
 * </p>
 *
 * @author rikad.ramadhan@rotterdam-cs.com
 * @see WebformColumn
 * @see com.rcs.dbservice.model.impl.WebformColumnImpl
 * @see com.rcs.dbservice.model.impl.WebformColumnModelImpl
 * @generated
 */
public interface WebformColumnModel extends BaseModel<WebformColumn> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a webform column model instance should use the {@link WebformColumn} interface instead.
	 */

	/**
	 * Returns the primary key of this webform column.
	 *
	 * @return the primary key of this webform column
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this webform column.
	 *
	 * @param primaryKey the primary key of this webform column
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the webform column ID of this webform column.
	 *
	 * @return the webform column ID of this webform column
	 */
	public long getWebformColumnId();

	/**
	 * Sets the webform column ID of this webform column.
	 *
	 * @param webformColumnId the webform column ID of this webform column
	 */
	public void setWebformColumnId(long webformColumnId);

	/**
	 * Returns the webform table ID of this webform column.
	 *
	 * @return the webform table ID of this webform column
	 */
	public long getWebformTableId();

	/**
	 * Sets the webform table ID of this webform column.
	 *
	 * @param webformTableId the webform table ID of this webform column
	 */
	public void setWebformTableId(long webformTableId);

	/**
	 * Returns the name of this webform column.
	 *
	 * @return the name of this webform column
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this webform column.
	 *
	 * @param name the name of this webform column
	 */
	public void setName(String name);

	/**
	 * Returns the type of this webform column.
	 *
	 * @return the type of this webform column
	 */
	public int getType();

	/**
	 * Sets the type of this webform column.
	 *
	 * @param type the type of this webform column
	 */
	public void setType(int type);

	/**
	 * Returns the input type of this webform column.
	 *
	 * @return the input type of this webform column
	 */
	public int getInputType();

	/**
	 * Sets the input type of this webform column.
	 *
	 * @param inputType the input type of this webform column
	 */
	public void setInputType(int inputType);

	/**
	 * Returns the is required of this webform column.
	 *
	 * @return the is required of this webform column
	 */
	public boolean getIsRequired();

	/**
	 * Returns <code>true</code> if this webform column is is required.
	 *
	 * @return <code>true</code> if this webform column is is required; <code>false</code> otherwise
	 */
	public boolean isIsRequired();

	/**
	 * Sets whether this webform column is is required.
	 *
	 * @param isRequired the is required of this webform column
	 */
	public void setIsRequired(boolean isRequired);

	/**
	 * Returns the place holder of this webform column.
	 *
	 * @return the place holder of this webform column
	 */
	@AutoEscape
	public String getPlaceHolder();

	/**
	 * Sets the place holder of this webform column.
	 *
	 * @param placeHolder the place holder of this webform column
	 */
	public void setPlaceHolder(String placeHolder);

	/**
	 * Returns the validation of this webform column.
	 *
	 * @return the validation of this webform column
	 */
	@AutoEscape
	public String getValidation();

	/**
	 * Sets the validation of this webform column.
	 *
	 * @param validation the validation of this webform column
	 */
	public void setValidation(String validation);

	/**
	 * Returns the custom validation of this webform column.
	 *
	 * @return the custom validation of this webform column
	 */
	@AutoEscape
	public String getCustomValidation();

	/**
	 * Sets the custom validation of this webform column.
	 *
	 * @param customValidation the custom validation of this webform column
	 */
	public void setCustomValidation(String customValidation);

	/**
	 * Returns the label class of this webform column.
	 *
	 * @return the label class of this webform column
	 */
	@AutoEscape
	public String getLabelClass();

	/**
	 * Sets the label class of this webform column.
	 *
	 * @param labelClass the label class of this webform column
	 */
	public void setLabelClass(String labelClass);

	/**
	 * Returns the input class of this webform column.
	 *
	 * @return the input class of this webform column
	 */
	@AutoEscape
	public String getInputClass();

	/**
	 * Sets the input class of this webform column.
	 *
	 * @param inputClass the input class of this webform column
	 */
	public void setInputClass(String inputClass);

	/**
	 * Returns the max length of this webform column.
	 *
	 * @return the max length of this webform column
	 */
	@AutoEscape
	public String getMaxLength();

	/**
	 * Sets the max length of this webform column.
	 *
	 * @param maxLength the max length of this webform column
	 */
	public void setMaxLength(String maxLength);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WebformColumn webformColumn);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WebformColumn> toCacheModel();

	@Override
	public WebformColumn toEscapedModel();

	@Override
	public WebformColumn toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}