/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.dbService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WebformTable service. Represents a row in the &quot;RcsWebform_WebformTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rcs.dbService.model.impl.WebformTableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rcs.dbService.model.impl.WebformTableImpl}.
 * </p>
 *
 * @author rikad.ramadhan@rotterdam-cs.com
 * @see WebformTable
 * @see com.rcs.dbService.model.impl.WebformTableImpl
 * @see com.rcs.dbService.model.impl.WebformTableModelImpl
 * @generated
 */
public interface WebformTableModel extends BaseModel<WebformTable> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a webform table model instance should use the {@link WebformTable} interface instead.
	 */

	/**
	 * Returns the primary key of this webform table.
	 *
	 * @return the primary key of this webform table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this webform table.
	 *
	 * @param primaryKey the primary key of this webform table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the webform table ID of this webform table.
	 *
	 * @return the webform table ID of this webform table
	 */
	public long getWebformTableId();

	/**
	 * Sets the webform table ID of this webform table.
	 *
	 * @param webformTableId the webform table ID of this webform table
	 */
	public void setWebformTableId(long webformTableId);

	/**
	 * Returns the portlet ID of this webform table.
	 *
	 * @return the portlet ID of this webform table
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this webform table.
	 *
	 * @param portletId the portlet ID of this webform table
	 */
	public void setPortletId(String portletId);

	/**
	 * Returns the webform counter of this webform table.
	 *
	 * @return the webform counter of this webform table
	 */
	@AutoEscape
	public String getWebformCounter();

	/**
	 * Sets the webform counter of this webform table.
	 *
	 * @param webformCounter the webform counter of this webform table
	 */
	public void setWebformCounter(String webformCounter);

	/**
	 * Returns the name of this webform table.
	 *
	 * @return the name of this webform table
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this webform table.
	 *
	 * @param name the name of this webform table
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WebformTable webformTable);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WebformTable> toCacheModel();

	@Override
	public WebformTable toEscapedModel();

	@Override
	public WebformTable toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}