/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.webform.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FormToPorletMap service. Represents a row in the &quot;rcswebform_FormToPorletMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rcs.webform.model.impl.FormToPorletMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rcs.webform.model.impl.FormToPorletMapImpl}.
 * </p>
 *
 * @author ryusuf
 * @see FormToPorletMap
 * @see com.rcs.webform.model.impl.FormToPorletMapImpl
 * @see com.rcs.webform.model.impl.FormToPorletMapModelImpl
 * @generated
 */
public interface FormToPorletMapModel extends BaseModel<FormToPorletMap>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form to porlet map model instance should use the {@link FormToPorletMap} interface instead.
	 */

	/**
	 * Returns the primary key of this form to porlet map.
	 *
	 * @return the primary key of this form to porlet map
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form to porlet map.
	 *
	 * @param primaryKey the primary key of this form to porlet map
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the form to porlet map ID of this form to porlet map.
	 *
	 * @return the form to porlet map ID of this form to porlet map
	 */
	public long getFormToPorletMapId();

	/**
	 * Sets the form to porlet map ID of this form to porlet map.
	 *
	 * @param formToPorletMapId the form to porlet map ID of this form to porlet map
	 */
	public void setFormToPorletMapId(long formToPorletMapId);

	/**
	 * Returns the group ID of this form to porlet map.
	 *
	 * @return the group ID of this form to porlet map
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this form to porlet map.
	 *
	 * @param groupId the group ID of this form to porlet map
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this form to porlet map.
	 *
	 * @return the company ID of this form to porlet map
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this form to porlet map.
	 *
	 * @param companyId the company ID of this form to porlet map
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this form to porlet map.
	 *
	 * @return the user ID of this form to porlet map
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this form to porlet map.
	 *
	 * @param userId the user ID of this form to porlet map
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this form to porlet map.
	 *
	 * @return the user uuid of this form to porlet map
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this form to porlet map.
	 *
	 * @param userUuid the user uuid of this form to porlet map
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this form to porlet map.
	 *
	 * @return the user name of this form to porlet map
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this form to porlet map.
	 *
	 * @param userName the user name of this form to porlet map
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this form to porlet map.
	 *
	 * @return the create date of this form to porlet map
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this form to porlet map.
	 *
	 * @param createDate the create date of this form to porlet map
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this form to porlet map.
	 *
	 * @return the modified date of this form to porlet map
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this form to porlet map.
	 *
	 * @param modifiedDate the modified date of this form to porlet map
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the form ID of this form to porlet map.
	 *
	 * @return the form ID of this form to porlet map
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this form to porlet map.
	 *
	 * @param formId the form ID of this form to porlet map
	 */
	public void setFormId(long formId);

	/**
	 * Returns the portlet ID of this form to porlet map.
	 *
	 * @return the portlet ID of this form to porlet map
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this form to porlet map.
	 *
	 * @param portletId the portlet ID of this form to porlet map
	 */
	public void setPortletId(String portletId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FormToPorletMap formToPorletMap);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FormToPorletMap> toCacheModel();

	@Override
	public FormToPorletMap toEscapedModel();

	@Override
	public FormToPorletMap toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}