/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.webform.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SubmittedData service. Represents a row in the &quot;rcswebform_SubmittedData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rcs.webform.model.impl.SubmittedDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rcs.webform.model.impl.SubmittedDataImpl}.
 * </p>
 *
 * @author ryusuf
 * @see SubmittedData
 * @see com.rcs.webform.model.impl.SubmittedDataImpl
 * @see com.rcs.webform.model.impl.SubmittedDataModelImpl
 * @generated
 */
public interface SubmittedDataModel extends BaseModel<SubmittedData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a submitted data model instance should use the {@link SubmittedData} interface instead.
	 */

	/**
	 * Returns the primary key of this submitted data.
	 *
	 * @return the primary key of this submitted data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this submitted data.
	 *
	 * @param primaryKey the primary key of this submitted data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the submitted data ID of this submitted data.
	 *
	 * @return the submitted data ID of this submitted data
	 */
	public long getSubmittedDataId();

	/**
	 * Sets the submitted data ID of this submitted data.
	 *
	 * @param submittedDataId the submitted data ID of this submitted data
	 */
	public void setSubmittedDataId(long submittedDataId);

	/**
	 * Returns the group ID of this submitted data.
	 *
	 * @return the group ID of this submitted data
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this submitted data.
	 *
	 * @param groupId the group ID of this submitted data
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this submitted data.
	 *
	 * @return the company ID of this submitted data
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this submitted data.
	 *
	 * @param companyId the company ID of this submitted data
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the active of this submitted data.
	 *
	 * @return the active of this submitted data
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this submitted data is active.
	 *
	 * @return <code>true</code> if this submitted data is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this submitted data is active.
	 *
	 * @param active the active of this submitted data
	 */
	public void setActive(boolean active);

	/**
	 * Returns the creation date of this submitted data.
	 *
	 * @return the creation date of this submitted data
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this submitted data.
	 *
	 * @param creationDate the creation date of this submitted data
	 */
	public void setCreationDate(Date creationDate);

	/**
	 * Returns the modification date of this submitted data.
	 *
	 * @return the modification date of this submitted data
	 */
	public Date getModificationDate();

	/**
	 * Sets the modification date of this submitted data.
	 *
	 * @param modificationDate the modification date of this submitted data
	 */
	public void setModificationDate(Date modificationDate);

	/**
	 * Returns the modification user of this submitted data.
	 *
	 * @return the modification user of this submitted data
	 */
	@AutoEscape
	public String getModificationUser();

	/**
	 * Sets the modification user of this submitted data.
	 *
	 * @param modificationUser the modification user of this submitted data
	 */
	public void setModificationUser(String modificationUser);

	/**
	 * Returns the form ID of this submitted data.
	 *
	 * @return the form ID of this submitted data
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this submitted data.
	 *
	 * @param formId the form ID of this submitted data
	 */
	public void setFormId(long formId);

	/**
	 * Returns the portlet ID of this submitted data.
	 *
	 * @return the portlet ID of this submitted data
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this submitted data.
	 *
	 * @param portletId the portlet ID of this submitted data
	 */
	public void setPortletId(String portletId);

	/**
	 * Returns the form item ID of this submitted data.
	 *
	 * @return the form item ID of this submitted data
	 */
	public long getFormItemId();

	/**
	 * Sets the form item ID of this submitted data.
	 *
	 * @param formItemId the form item ID of this submitted data
	 */
	public void setFormItemId(long formItemId);

	/**
	 * Returns the user input of this submitted data.
	 *
	 * @return the user input of this submitted data
	 */
	@AutoEscape
	public String getUserInput();

	/**
	 * Sets the user input of this submitted data.
	 *
	 * @param userInput the user input of this submitted data
	 */
	public void setUserInput(String userInput);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SubmittedData submittedData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SubmittedData> toCacheModel();

	@Override
	public SubmittedData toEscapedModel();

	@Override
	public SubmittedData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}