/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.webform.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rcs.webform.model.FormItem;
import com.rcs.webform.service.FormItemLocalServiceUtil;

/**
 * The extended model base implementation for the FormItem service. Represents a row in the &quot;rcswebform_FormItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormItemImpl}.
 * </p>
 *
 * @author ryusuf
 * @see FormItemImpl
 * @see com.rcs.webform.model.FormItem
 * @generated
 */
public abstract class FormItemBaseImpl extends FormItemModelImpl
	implements FormItem {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form item model instance should use the {@link FormItem} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			FormItemLocalServiceUtil.addFormItem(this);
		}
		else {
			FormItemLocalServiceUtil.updateFormItem(this);
		}
	}
}