/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.webform.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rcs.webform.model.FormToPorletMap;
import com.rcs.webform.service.FormToPorletMapLocalServiceUtil;

/**
 * The extended model base implementation for the FormToPorletMap service. Represents a row in the &quot;rcswebform_FormToPorletMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormToPorletMapImpl}.
 * </p>
 *
 * @author ryusuf
 * @see FormToPorletMapImpl
 * @see com.rcs.webform.model.FormToPorletMap
 * @generated
 */
public abstract class FormToPorletMapBaseImpl extends FormToPorletMapModelImpl
	implements FormToPorletMap {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form to porlet map model instance should use the {@link FormToPorletMap} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			FormToPorletMapLocalServiceUtil.addFormToPorletMap(this);
		}
		else {
			FormToPorletMapLocalServiceUtil.updateFormToPorletMap(this);
		}
	}
}