/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.webform.model.impl;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rcs.webform.model.FormItem;
import com.rcs.webform.model.FormItemModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the FormItem service. Represents a row in the &quot;rcswebform_FormItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rcs.webform.model.FormItemModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormItemImpl}.
 * </p>
 *
 * @author ryusuf
 * @see FormItemImpl
 * @see com.rcs.webform.model.FormItem
 * @see com.rcs.webform.model.FormItemModel
 * @generated
 */
public class FormItemModelImpl extends BaseModelImpl<FormItem>
	implements FormItemModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form item model instance should use the {@link com.rcs.webform.model.FormItem} interface instead.
	 */
	public static final String TABLE_NAME = "rcswebform_FormItem";
	public static final Object[][] TABLE_COLUMNS = {
			{ "formItemId", Types.BIGINT },
			{ "active_", Types.BOOLEAN },
			{ "creationDate", Types.TIMESTAMP },
			{ "modificationDate", Types.TIMESTAMP },
			{ "modificationUser", Types.VARCHAR },
			{ "formId", Types.BIGINT },
			{ "formItemAttrId", Types.VARCHAR },
			{ "formItemAttrClass", Types.VARCHAR },
			{ "label", Types.VARCHAR },
			{ "labelAttrId", Types.VARCHAR },
			{ "labelAttrClass", Types.VARCHAR },
			{ "inputAttrId", Types.VARCHAR },
			{ "inputAttrClass", Types.VARCHAR },
			{ "type_", Types.VARCHAR },
			{ "optionKeys", Types.VARCHAR },
			{ "optionValues", Types.VARCHAR },
			{ "mandatory", Types.BOOLEAN },
			{ "defaultValue", Types.VARCHAR },
			{ "order_", Types.INTEGER },
			{ "validationType", Types.VARCHAR },
			{ "validationRegexValue", Types.VARCHAR },
			{ "minLength", Types.INTEGER },
			{ "maxLength", Types.INTEGER },
			{ "errorValidationMessage", Types.VARCHAR },
			{ "errorMandatoryMessage", Types.VARCHAR },
			{ "errorLengthMessage", Types.VARCHAR },
			{ "hintMessage", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table rcswebform_FormItem (formItemId LONG not null primary key,active_ BOOLEAN,creationDate DATE null,modificationDate DATE null,modificationUser VARCHAR(75) null,formId LONG,formItemAttrId VARCHAR(75) null,formItemAttrClass VARCHAR(75) null,label STRING null,labelAttrId VARCHAR(75) null,labelAttrClass VARCHAR(75) null,inputAttrId VARCHAR(75) null,inputAttrClass VARCHAR(75) null,type_ VARCHAR(75) null,optionKeys VARCHAR(75) null,optionValues STRING null,mandatory BOOLEAN,defaultValue STRING null,order_ INTEGER,validationType VARCHAR(75) null,validationRegexValue VARCHAR(75) null,minLength INTEGER,maxLength INTEGER,errorValidationMessage STRING null,errorMandatoryMessage STRING null,errorLengthMessage STRING null,hintMessage STRING null)";
	public static final String TABLE_SQL_DROP = "drop table rcswebform_FormItem";
	public static final String ORDER_BY_JPQL = " ORDER BY formItem.formItemId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY rcswebform_FormItem.formItemId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rcs.webform.model.FormItem"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rcs.webform.model.FormItem"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rcs.webform.model.FormItem"),
			true);
	public static long FORMID_COLUMN_BITMASK = 1L;
	public static long FORMITEMID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rcs.webform.model.FormItem"));

	public FormItemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _formItemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFormItemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _formItemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FormItem.class;
	}

	@Override
	public String getModelClassName() {
		return FormItem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("formItemId", getFormItemId());
		attributes.put("active", getActive());
		attributes.put("creationDate", getCreationDate());
		attributes.put("modificationDate", getModificationDate());
		attributes.put("modificationUser", getModificationUser());
		attributes.put("formId", getFormId());
		attributes.put("formItemAttrId", getFormItemAttrId());
		attributes.put("formItemAttrClass", getFormItemAttrClass());
		attributes.put("label", getLabel());
		attributes.put("labelAttrId", getLabelAttrId());
		attributes.put("labelAttrClass", getLabelAttrClass());
		attributes.put("inputAttrId", getInputAttrId());
		attributes.put("inputAttrClass", getInputAttrClass());
		attributes.put("type", getType());
		attributes.put("optionKeys", getOptionKeys());
		attributes.put("optionValues", getOptionValues());
		attributes.put("mandatory", getMandatory());
		attributes.put("defaultValue", getDefaultValue());
		attributes.put("order", getOrder());
		attributes.put("validationType", getValidationType());
		attributes.put("validationRegexValue", getValidationRegexValue());
		attributes.put("minLength", getMinLength());
		attributes.put("maxLength", getMaxLength());
		attributes.put("errorValidationMessage", getErrorValidationMessage());
		attributes.put("errorMandatoryMessage", getErrorMandatoryMessage());
		attributes.put("errorLengthMessage", getErrorLengthMessage());
		attributes.put("hintMessage", getHintMessage());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long formItemId = (Long)attributes.get("formItemId");

		if (formItemId != null) {
			setFormItemId(formItemId);
		}

		Boolean active = (Boolean)attributes.get("active");

		if (active != null) {
			setActive(active);
		}

		Date creationDate = (Date)attributes.get("creationDate");

		if (creationDate != null) {
			setCreationDate(creationDate);
		}

		Date modificationDate = (Date)attributes.get("modificationDate");

		if (modificationDate != null) {
			setModificationDate(modificationDate);
		}

		String modificationUser = (String)attributes.get("modificationUser");

		if (modificationUser != null) {
			setModificationUser(modificationUser);
		}

		Long formId = (Long)attributes.get("formId");

		if (formId != null) {
			setFormId(formId);
		}

		String formItemAttrId = (String)attributes.get("formItemAttrId");

		if (formItemAttrId != null) {
			setFormItemAttrId(formItemAttrId);
		}

		String formItemAttrClass = (String)attributes.get("formItemAttrClass");

		if (formItemAttrClass != null) {
			setFormItemAttrClass(formItemAttrClass);
		}

		String label = (String)attributes.get("label");

		if (label != null) {
			setLabel(label);
		}

		String labelAttrId = (String)attributes.get("labelAttrId");

		if (labelAttrId != null) {
			setLabelAttrId(labelAttrId);
		}

		String labelAttrClass = (String)attributes.get("labelAttrClass");

		if (labelAttrClass != null) {
			setLabelAttrClass(labelAttrClass);
		}

		String inputAttrId = (String)attributes.get("inputAttrId");

		if (inputAttrId != null) {
			setInputAttrId(inputAttrId);
		}

		String inputAttrClass = (String)attributes.get("inputAttrClass");

		if (inputAttrClass != null) {
			setInputAttrClass(inputAttrClass);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String optionKeys = (String)attributes.get("optionKeys");

		if (optionKeys != null) {
			setOptionKeys(optionKeys);
		}

		String optionValues = (String)attributes.get("optionValues");

		if (optionValues != null) {
			setOptionValues(optionValues);
		}

		Boolean mandatory = (Boolean)attributes.get("mandatory");

		if (mandatory != null) {
			setMandatory(mandatory);
		}

		String defaultValue = (String)attributes.get("defaultValue");

		if (defaultValue != null) {
			setDefaultValue(defaultValue);
		}

		Integer order = (Integer)attributes.get("order");

		if (order != null) {
			setOrder(order);
		}

		String validationType = (String)attributes.get("validationType");

		if (validationType != null) {
			setValidationType(validationType);
		}

		String validationRegexValue = (String)attributes.get(
				"validationRegexValue");

		if (validationRegexValue != null) {
			setValidationRegexValue(validationRegexValue);
		}

		Integer minLength = (Integer)attributes.get("minLength");

		if (minLength != null) {
			setMinLength(minLength);
		}

		Integer maxLength = (Integer)attributes.get("maxLength");

		if (maxLength != null) {
			setMaxLength(maxLength);
		}

		String errorValidationMessage = (String)attributes.get(
				"errorValidationMessage");

		if (errorValidationMessage != null) {
			setErrorValidationMessage(errorValidationMessage);
		}

		String errorMandatoryMessage = (String)attributes.get(
				"errorMandatoryMessage");

		if (errorMandatoryMessage != null) {
			setErrorMandatoryMessage(errorMandatoryMessage);
		}

		String errorLengthMessage = (String)attributes.get("errorLengthMessage");

		if (errorLengthMessage != null) {
			setErrorLengthMessage(errorLengthMessage);
		}

		String hintMessage = (String)attributes.get("hintMessage");

		if (hintMessage != null) {
			setHintMessage(hintMessage);
		}
	}

	@Override
	public long getFormItemId() {
		return _formItemId;
	}

	@Override
	public void setFormItemId(long formItemId) {
		_formItemId = formItemId;
	}

	@Override
	public boolean getActive() {
		return _active;
	}

	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_active = active;
	}

	@Override
	public Date getCreationDate() {
		return _creationDate;
	}

	@Override
	public void setCreationDate(Date creationDate) {
		_creationDate = creationDate;
	}

	@Override
	public Date getModificationDate() {
		return _modificationDate;
	}

	@Override
	public void setModificationDate(Date modificationDate) {
		_modificationDate = modificationDate;
	}

	@Override
	public String getModificationUser() {
		if (_modificationUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _modificationUser;
		}
	}

	@Override
	public void setModificationUser(String modificationUser) {
		_modificationUser = modificationUser;
	}

	@Override
	public long getFormId() {
		return _formId;
	}

	@Override
	public void setFormId(long formId) {
		_columnBitmask |= FORMID_COLUMN_BITMASK;

		if (!_setOriginalFormId) {
			_setOriginalFormId = true;

			_originalFormId = _formId;
		}

		_formId = formId;
	}

	public long getOriginalFormId() {
		return _originalFormId;
	}

	@Override
	public String getFormItemAttrId() {
		if (_formItemAttrId == null) {
			return StringPool.BLANK;
		}
		else {
			return _formItemAttrId;
		}
	}

	@Override
	public void setFormItemAttrId(String formItemAttrId) {
		_formItemAttrId = formItemAttrId;
	}

	@Override
	public String getFormItemAttrClass() {
		if (_formItemAttrClass == null) {
			return StringPool.BLANK;
		}
		else {
			return _formItemAttrClass;
		}
	}

	@Override
	public void setFormItemAttrClass(String formItemAttrClass) {
		_formItemAttrClass = formItemAttrClass;
	}

	@Override
	public String getLabel() {
		if (_label == null) {
			return StringPool.BLANK;
		}
		else {
			return _label;
		}
	}

	@Override
	public String getLabel(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLabel(languageId);
	}

	@Override
	public String getLabel(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLabel(languageId, useDefault);
	}

	@Override
	public String getLabel(String languageId) {
		return LocalizationUtil.getLocalization(getLabel(), languageId);
	}

	@Override
	public String getLabel(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getLabel(), languageId,
			useDefault);
	}

	@Override
	public String getLabelCurrentLanguageId() {
		return _labelCurrentLanguageId;
	}

	@JSON
	@Override
	public String getLabelCurrentValue() {
		Locale locale = getLocale(_labelCurrentLanguageId);

		return getLabel(locale);
	}

	@Override
	public Map<Locale, String> getLabelMap() {
		return LocalizationUtil.getLocalizationMap(getLabel());
	}

	@Override
	public void setLabel(String label) {
		_label = label;
	}

	@Override
	public void setLabel(String label, Locale locale) {
		setLabel(label, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setLabel(String label, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(label)) {
			setLabel(LocalizationUtil.updateLocalization(getLabel(), "Label",
					label, languageId, defaultLanguageId));
		}
		else {
			setLabel(LocalizationUtil.removeLocalization(getLabel(), "Label",
					languageId));
		}
	}

	@Override
	public void setLabelCurrentLanguageId(String languageId) {
		_labelCurrentLanguageId = languageId;
	}

	@Override
	public void setLabelMap(Map<Locale, String> labelMap) {
		setLabelMap(labelMap, LocaleUtil.getDefault());
	}

	@Override
	public void setLabelMap(Map<Locale, String> labelMap, Locale defaultLocale) {
		if (labelMap == null) {
			return;
		}

		setLabel(LocalizationUtil.updateLocalization(labelMap, getLabel(),
				"Label", LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getLabelAttrId() {
		if (_labelAttrId == null) {
			return StringPool.BLANK;
		}
		else {
			return _labelAttrId;
		}
	}

	@Override
	public void setLabelAttrId(String labelAttrId) {
		_labelAttrId = labelAttrId;
	}

	@Override
	public String getLabelAttrClass() {
		if (_labelAttrClass == null) {
			return StringPool.BLANK;
		}
		else {
			return _labelAttrClass;
		}
	}

	@Override
	public void setLabelAttrClass(String labelAttrClass) {
		_labelAttrClass = labelAttrClass;
	}

	@Override
	public String getInputAttrId() {
		if (_inputAttrId == null) {
			return StringPool.BLANK;
		}
		else {
			return _inputAttrId;
		}
	}

	@Override
	public void setInputAttrId(String inputAttrId) {
		_inputAttrId = inputAttrId;
	}

	@Override
	public String getInputAttrClass() {
		if (_inputAttrClass == null) {
			return StringPool.BLANK;
		}
		else {
			return _inputAttrClass;
		}
	}

	@Override
	public void setInputAttrClass(String inputAttrClass) {
		_inputAttrClass = inputAttrClass;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@Override
	public String getOptionKeys() {
		if (_optionKeys == null) {
			return StringPool.BLANK;
		}
		else {
			return _optionKeys;
		}
	}

	@Override
	public void setOptionKeys(String optionKeys) {
		_optionKeys = optionKeys;
	}

	@Override
	public String getOptionValues() {
		if (_optionValues == null) {
			return StringPool.BLANK;
		}
		else {
			return _optionValues;
		}
	}

	@Override
	public String getOptionValues(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getOptionValues(languageId);
	}

	@Override
	public String getOptionValues(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getOptionValues(languageId, useDefault);
	}

	@Override
	public String getOptionValues(String languageId) {
		return LocalizationUtil.getLocalization(getOptionValues(), languageId);
	}

	@Override
	public String getOptionValues(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getOptionValues(), languageId,
			useDefault);
	}

	@Override
	public String getOptionValuesCurrentLanguageId() {
		return _optionValuesCurrentLanguageId;
	}

	@JSON
	@Override
	public String getOptionValuesCurrentValue() {
		Locale locale = getLocale(_optionValuesCurrentLanguageId);

		return getOptionValues(locale);
	}

	@Override
	public Map<Locale, String> getOptionValuesMap() {
		return LocalizationUtil.getLocalizationMap(getOptionValues());
	}

	@Override
	public void setOptionValues(String optionValues) {
		_optionValues = optionValues;
	}

	@Override
	public void setOptionValues(String optionValues, Locale locale) {
		setOptionValues(optionValues, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setOptionValues(String optionValues, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(optionValues)) {
			setOptionValues(LocalizationUtil.updateLocalization(
					getOptionValues(), "OptionValues", optionValues,
					languageId, defaultLanguageId));
		}
		else {
			setOptionValues(LocalizationUtil.removeLocalization(
					getOptionValues(), "OptionValues", languageId));
		}
	}

	@Override
	public void setOptionValuesCurrentLanguageId(String languageId) {
		_optionValuesCurrentLanguageId = languageId;
	}

	@Override
	public void setOptionValuesMap(Map<Locale, String> optionValuesMap) {
		setOptionValuesMap(optionValuesMap, LocaleUtil.getDefault());
	}

	@Override
	public void setOptionValuesMap(Map<Locale, String> optionValuesMap,
		Locale defaultLocale) {
		if (optionValuesMap == null) {
			return;
		}

		setOptionValues(LocalizationUtil.updateLocalization(optionValuesMap,
				getOptionValues(), "OptionValues",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public boolean getMandatory() {
		return _mandatory;
	}

	@Override
	public boolean isMandatory() {
		return _mandatory;
	}

	@Override
	public void setMandatory(boolean mandatory) {
		_mandatory = mandatory;
	}

	@Override
	public String getDefaultValue() {
		if (_defaultValue == null) {
			return StringPool.BLANK;
		}
		else {
			return _defaultValue;
		}
	}

	@Override
	public String getDefaultValue(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDefaultValue(languageId);
	}

	@Override
	public String getDefaultValue(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDefaultValue(languageId, useDefault);
	}

	@Override
	public String getDefaultValue(String languageId) {
		return LocalizationUtil.getLocalization(getDefaultValue(), languageId);
	}

	@Override
	public String getDefaultValue(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getDefaultValue(), languageId,
			useDefault);
	}

	@Override
	public String getDefaultValueCurrentLanguageId() {
		return _defaultValueCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDefaultValueCurrentValue() {
		Locale locale = getLocale(_defaultValueCurrentLanguageId);

		return getDefaultValue(locale);
	}

	@Override
	public Map<Locale, String> getDefaultValueMap() {
		return LocalizationUtil.getLocalizationMap(getDefaultValue());
	}

	@Override
	public void setDefaultValue(String defaultValue) {
		_defaultValue = defaultValue;
	}

	@Override
	public void setDefaultValue(String defaultValue, Locale locale) {
		setDefaultValue(defaultValue, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setDefaultValue(String defaultValue, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(defaultValue)) {
			setDefaultValue(LocalizationUtil.updateLocalization(
					getDefaultValue(), "DefaultValue", defaultValue,
					languageId, defaultLanguageId));
		}
		else {
			setDefaultValue(LocalizationUtil.removeLocalization(
					getDefaultValue(), "DefaultValue", languageId));
		}
	}

	@Override
	public void setDefaultValueCurrentLanguageId(String languageId) {
		_defaultValueCurrentLanguageId = languageId;
	}

	@Override
	public void setDefaultValueMap(Map<Locale, String> defaultValueMap) {
		setDefaultValueMap(defaultValueMap, LocaleUtil.getDefault());
	}

	@Override
	public void setDefaultValueMap(Map<Locale, String> defaultValueMap,
		Locale defaultLocale) {
		if (defaultValueMap == null) {
			return;
		}

		setDefaultValue(LocalizationUtil.updateLocalization(defaultValueMap,
				getDefaultValue(), "DefaultValue",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public int getOrder() {
		return _order;
	}

	@Override
	public void setOrder(int order) {
		_order = order;
	}

	@Override
	public String getValidationType() {
		if (_validationType == null) {
			return StringPool.BLANK;
		}
		else {
			return _validationType;
		}
	}

	@Override
	public void setValidationType(String validationType) {
		_validationType = validationType;
	}

	@Override
	public String getValidationRegexValue() {
		if (_validationRegexValue == null) {
			return StringPool.BLANK;
		}
		else {
			return _validationRegexValue;
		}
	}

	@Override
	public void setValidationRegexValue(String validationRegexValue) {
		_validationRegexValue = validationRegexValue;
	}

	@Override
	public int getMinLength() {
		return _minLength;
	}

	@Override
	public void setMinLength(int minLength) {
		_minLength = minLength;
	}

	@Override
	public int getMaxLength() {
		return _maxLength;
	}

	@Override
	public void setMaxLength(int maxLength) {
		_maxLength = maxLength;
	}

	@Override
	public String getErrorValidationMessage() {
		if (_errorValidationMessage == null) {
			return StringPool.BLANK;
		}
		else {
			return _errorValidationMessage;
		}
	}

	@Override
	public String getErrorValidationMessage(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getErrorValidationMessage(languageId);
	}

	@Override
	public String getErrorValidationMessage(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getErrorValidationMessage(languageId, useDefault);
	}

	@Override
	public String getErrorValidationMessage(String languageId) {
		return LocalizationUtil.getLocalization(getErrorValidationMessage(),
			languageId);
	}

	@Override
	public String getErrorValidationMessage(String languageId,
		boolean useDefault) {
		return LocalizationUtil.getLocalization(getErrorValidationMessage(),
			languageId, useDefault);
	}

	@Override
	public String getErrorValidationMessageCurrentLanguageId() {
		return _errorValidationMessageCurrentLanguageId;
	}

	@JSON
	@Override
	public String getErrorValidationMessageCurrentValue() {
		Locale locale = getLocale(_errorValidationMessageCurrentLanguageId);

		return getErrorValidationMessage(locale);
	}

	@Override
	public Map<Locale, String> getErrorValidationMessageMap() {
		return LocalizationUtil.getLocalizationMap(getErrorValidationMessage());
	}

	@Override
	public void setErrorValidationMessage(String errorValidationMessage) {
		_errorValidationMessage = errorValidationMessage;
	}

	@Override
	public void setErrorValidationMessage(String errorValidationMessage,
		Locale locale) {
		setErrorValidationMessage(errorValidationMessage, locale,
			LocaleUtil.getDefault());
	}

	@Override
	public void setErrorValidationMessage(String errorValidationMessage,
		Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(errorValidationMessage)) {
			setErrorValidationMessage(LocalizationUtil.updateLocalization(
					getErrorValidationMessage(), "ErrorValidationMessage",
					errorValidationMessage, languageId, defaultLanguageId));
		}
		else {
			setErrorValidationMessage(LocalizationUtil.removeLocalization(
					getErrorValidationMessage(), "ErrorValidationMessage",
					languageId));
		}
	}

	@Override
	public void setErrorValidationMessageCurrentLanguageId(String languageId) {
		_errorValidationMessageCurrentLanguageId = languageId;
	}

	@Override
	public void setErrorValidationMessageMap(
		Map<Locale, String> errorValidationMessageMap) {
		setErrorValidationMessageMap(errorValidationMessageMap,
			LocaleUtil.getDefault());
	}

	@Override
	public void setErrorValidationMessageMap(
		Map<Locale, String> errorValidationMessageMap, Locale defaultLocale) {
		if (errorValidationMessageMap == null) {
			return;
		}

		setErrorValidationMessage(LocalizationUtil.updateLocalization(
				errorValidationMessageMap, getErrorValidationMessage(),
				"ErrorValidationMessage", LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getErrorMandatoryMessage() {
		if (_errorMandatoryMessage == null) {
			return StringPool.BLANK;
		}
		else {
			return _errorMandatoryMessage;
		}
	}

	@Override
	public String getErrorMandatoryMessage(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getErrorMandatoryMessage(languageId);
	}

	@Override
	public String getErrorMandatoryMessage(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getErrorMandatoryMessage(languageId, useDefault);
	}

	@Override
	public String getErrorMandatoryMessage(String languageId) {
		return LocalizationUtil.getLocalization(getErrorMandatoryMessage(),
			languageId);
	}

	@Override
	public String getErrorMandatoryMessage(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getErrorMandatoryMessage(),
			languageId, useDefault);
	}

	@Override
	public String getErrorMandatoryMessageCurrentLanguageId() {
		return _errorMandatoryMessageCurrentLanguageId;
	}

	@JSON
	@Override
	public String getErrorMandatoryMessageCurrentValue() {
		Locale locale = getLocale(_errorMandatoryMessageCurrentLanguageId);

		return getErrorMandatoryMessage(locale);
	}

	@Override
	public Map<Locale, String> getErrorMandatoryMessageMap() {
		return LocalizationUtil.getLocalizationMap(getErrorMandatoryMessage());
	}

	@Override
	public void setErrorMandatoryMessage(String errorMandatoryMessage) {
		_errorMandatoryMessage = errorMandatoryMessage;
	}

	@Override
	public void setErrorMandatoryMessage(String errorMandatoryMessage,
		Locale locale) {
		setErrorMandatoryMessage(errorMandatoryMessage, locale,
			LocaleUtil.getDefault());
	}

	@Override
	public void setErrorMandatoryMessage(String errorMandatoryMessage,
		Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(errorMandatoryMessage)) {
			setErrorMandatoryMessage(LocalizationUtil.updateLocalization(
					getErrorMandatoryMessage(), "ErrorMandatoryMessage",
					errorMandatoryMessage, languageId, defaultLanguageId));
		}
		else {
			setErrorMandatoryMessage(LocalizationUtil.removeLocalization(
					getErrorMandatoryMessage(), "ErrorMandatoryMessage",
					languageId));
		}
	}

	@Override
	public void setErrorMandatoryMessageCurrentLanguageId(String languageId) {
		_errorMandatoryMessageCurrentLanguageId = languageId;
	}

	@Override
	public void setErrorMandatoryMessageMap(
		Map<Locale, String> errorMandatoryMessageMap) {
		setErrorMandatoryMessageMap(errorMandatoryMessageMap,
			LocaleUtil.getDefault());
	}

	@Override
	public void setErrorMandatoryMessageMap(
		Map<Locale, String> errorMandatoryMessageMap, Locale defaultLocale) {
		if (errorMandatoryMessageMap == null) {
			return;
		}

		setErrorMandatoryMessage(LocalizationUtil.updateLocalization(
				errorMandatoryMessageMap, getErrorMandatoryMessage(),
				"ErrorMandatoryMessage", LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getErrorLengthMessage() {
		if (_errorLengthMessage == null) {
			return StringPool.BLANK;
		}
		else {
			return _errorLengthMessage;
		}
	}

	@Override
	public String getErrorLengthMessage(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getErrorLengthMessage(languageId);
	}

	@Override
	public String getErrorLengthMessage(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getErrorLengthMessage(languageId, useDefault);
	}

	@Override
	public String getErrorLengthMessage(String languageId) {
		return LocalizationUtil.getLocalization(getErrorLengthMessage(),
			languageId);
	}

	@Override
	public String getErrorLengthMessage(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getErrorLengthMessage(),
			languageId, useDefault);
	}

	@Override
	public String getErrorLengthMessageCurrentLanguageId() {
		return _errorLengthMessageCurrentLanguageId;
	}

	@JSON
	@Override
	public String getErrorLengthMessageCurrentValue() {
		Locale locale = getLocale(_errorLengthMessageCurrentLanguageId);

		return getErrorLengthMessage(locale);
	}

	@Override
	public Map<Locale, String> getErrorLengthMessageMap() {
		return LocalizationUtil.getLocalizationMap(getErrorLengthMessage());
	}

	@Override
	public void setErrorLengthMessage(String errorLengthMessage) {
		_errorLengthMessage = errorLengthMessage;
	}

	@Override
	public void setErrorLengthMessage(String errorLengthMessage, Locale locale) {
		setErrorLengthMessage(errorLengthMessage, locale,
			LocaleUtil.getDefault());
	}

	@Override
	public void setErrorLengthMessage(String errorLengthMessage, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(errorLengthMessage)) {
			setErrorLengthMessage(LocalizationUtil.updateLocalization(
					getErrorLengthMessage(), "ErrorLengthMessage",
					errorLengthMessage, languageId, defaultLanguageId));
		}
		else {
			setErrorLengthMessage(LocalizationUtil.removeLocalization(
					getErrorLengthMessage(), "ErrorLengthMessage", languageId));
		}
	}

	@Override
	public void setErrorLengthMessageCurrentLanguageId(String languageId) {
		_errorLengthMessageCurrentLanguageId = languageId;
	}

	@Override
	public void setErrorLengthMessageMap(
		Map<Locale, String> errorLengthMessageMap) {
		setErrorLengthMessageMap(errorLengthMessageMap, LocaleUtil.getDefault());
	}

	@Override
	public void setErrorLengthMessageMap(
		Map<Locale, String> errorLengthMessageMap, Locale defaultLocale) {
		if (errorLengthMessageMap == null) {
			return;
		}

		setErrorLengthMessage(LocalizationUtil.updateLocalization(
				errorLengthMessageMap, getErrorLengthMessage(),
				"ErrorLengthMessage", LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getHintMessage() {
		if (_hintMessage == null) {
			return StringPool.BLANK;
		}
		else {
			return _hintMessage;
		}
	}

	@Override
	public String getHintMessage(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getHintMessage(languageId);
	}

	@Override
	public String getHintMessage(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getHintMessage(languageId, useDefault);
	}

	@Override
	public String getHintMessage(String languageId) {
		return LocalizationUtil.getLocalization(getHintMessage(), languageId);
	}

	@Override
	public String getHintMessage(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getHintMessage(), languageId,
			useDefault);
	}

	@Override
	public String getHintMessageCurrentLanguageId() {
		return _hintMessageCurrentLanguageId;
	}

	@JSON
	@Override
	public String getHintMessageCurrentValue() {
		Locale locale = getLocale(_hintMessageCurrentLanguageId);

		return getHintMessage(locale);
	}

	@Override
	public Map<Locale, String> getHintMessageMap() {
		return LocalizationUtil.getLocalizationMap(getHintMessage());
	}

	@Override
	public void setHintMessage(String hintMessage) {
		_hintMessage = hintMessage;
	}

	@Override
	public void setHintMessage(String hintMessage, Locale locale) {
		setHintMessage(hintMessage, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setHintMessage(String hintMessage, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(hintMessage)) {
			setHintMessage(LocalizationUtil.updateLocalization(
					getHintMessage(), "HintMessage", hintMessage, languageId,
					defaultLanguageId));
		}
		else {
			setHintMessage(LocalizationUtil.removeLocalization(
					getHintMessage(), "HintMessage", languageId));
		}
	}

	@Override
	public void setHintMessageCurrentLanguageId(String languageId) {
		_hintMessageCurrentLanguageId = languageId;
	}

	@Override
	public void setHintMessageMap(Map<Locale, String> hintMessageMap) {
		setHintMessageMap(hintMessageMap, LocaleUtil.getDefault());
	}

	@Override
	public void setHintMessageMap(Map<Locale, String> hintMessageMap,
		Locale defaultLocale) {
		if (hintMessageMap == null) {
			return;
		}

		setHintMessage(LocalizationUtil.updateLocalization(hintMessageMap,
				getHintMessage(), "HintMessage",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FormItem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> labelMap = getLabelMap();

		for (Map.Entry<Locale, String> entry : labelMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> optionValuesMap = getOptionValuesMap();

		for (Map.Entry<Locale, String> entry : optionValuesMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> defaultValueMap = getDefaultValueMap();

		for (Map.Entry<Locale, String> entry : defaultValueMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> errorValidationMessageMap = getErrorValidationMessageMap();

		for (Map.Entry<Locale, String> entry : errorValidationMessageMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> errorMandatoryMessageMap = getErrorMandatoryMessageMap();

		for (Map.Entry<Locale, String> entry : errorMandatoryMessageMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> errorLengthMessageMap = getErrorLengthMessageMap();

		for (Map.Entry<Locale, String> entry : errorLengthMessageMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> hintMessageMap = getHintMessageMap();

		for (Map.Entry<Locale, String> entry : hintMessageMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getLabel();

		if (xml == null) {
			return StringPool.BLANK;
		}

		return LocalizationUtil.getDefaultLanguageId(xml);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		prepareLocalizedFieldsForImport(null);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String label = getLabel(defaultLocale);

		if (Validator.isNull(label)) {
			setLabel(getLabel(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setLabel(getLabel(defaultLocale), defaultLocale, defaultLocale);
		}

		String optionValues = getOptionValues(defaultLocale);

		if (Validator.isNull(optionValues)) {
			setOptionValues(getOptionValues(modelDefaultLanguageId),
				defaultLocale);
		}
		else {
			setOptionValues(getOptionValues(defaultLocale), defaultLocale,
				defaultLocale);
		}

		String defaultValue = getDefaultValue(defaultLocale);

		if (Validator.isNull(defaultValue)) {
			setDefaultValue(getDefaultValue(modelDefaultLanguageId),
				defaultLocale);
		}
		else {
			setDefaultValue(getDefaultValue(defaultLocale), defaultLocale,
				defaultLocale);
		}

		String errorValidationMessage = getErrorValidationMessage(defaultLocale);

		if (Validator.isNull(errorValidationMessage)) {
			setErrorValidationMessage(getErrorValidationMessage(
					modelDefaultLanguageId), defaultLocale);
		}
		else {
			setErrorValidationMessage(getErrorValidationMessage(defaultLocale),
				defaultLocale, defaultLocale);
		}

		String errorMandatoryMessage = getErrorMandatoryMessage(defaultLocale);

		if (Validator.isNull(errorMandatoryMessage)) {
			setErrorMandatoryMessage(getErrorMandatoryMessage(
					modelDefaultLanguageId), defaultLocale);
		}
		else {
			setErrorMandatoryMessage(getErrorMandatoryMessage(defaultLocale),
				defaultLocale, defaultLocale);
		}

		String errorLengthMessage = getErrorLengthMessage(defaultLocale);

		if (Validator.isNull(errorLengthMessage)) {
			setErrorLengthMessage(getErrorLengthMessage(modelDefaultLanguageId),
				defaultLocale);
		}
		else {
			setErrorLengthMessage(getErrorLengthMessage(defaultLocale),
				defaultLocale, defaultLocale);
		}

		String hintMessage = getHintMessage(defaultLocale);

		if (Validator.isNull(hintMessage)) {
			setHintMessage(getHintMessage(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setHintMessage(getHintMessage(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public FormItem toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FormItem)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FormItemImpl formItemImpl = new FormItemImpl();

		formItemImpl.setFormItemId(getFormItemId());
		formItemImpl.setActive(getActive());
		formItemImpl.setCreationDate(getCreationDate());
		formItemImpl.setModificationDate(getModificationDate());
		formItemImpl.setModificationUser(getModificationUser());
		formItemImpl.setFormId(getFormId());
		formItemImpl.setFormItemAttrId(getFormItemAttrId());
		formItemImpl.setFormItemAttrClass(getFormItemAttrClass());
		formItemImpl.setLabel(getLabel());
		formItemImpl.setLabelAttrId(getLabelAttrId());
		formItemImpl.setLabelAttrClass(getLabelAttrClass());
		formItemImpl.setInputAttrId(getInputAttrId());
		formItemImpl.setInputAttrClass(getInputAttrClass());
		formItemImpl.setType(getType());
		formItemImpl.setOptionKeys(getOptionKeys());
		formItemImpl.setOptionValues(getOptionValues());
		formItemImpl.setMandatory(getMandatory());
		formItemImpl.setDefaultValue(getDefaultValue());
		formItemImpl.setOrder(getOrder());
		formItemImpl.setValidationType(getValidationType());
		formItemImpl.setValidationRegexValue(getValidationRegexValue());
		formItemImpl.setMinLength(getMinLength());
		formItemImpl.setMaxLength(getMaxLength());
		formItemImpl.setErrorValidationMessage(getErrorValidationMessage());
		formItemImpl.setErrorMandatoryMessage(getErrorMandatoryMessage());
		formItemImpl.setErrorLengthMessage(getErrorLengthMessage());
		formItemImpl.setHintMessage(getHintMessage());

		formItemImpl.resetOriginalValues();

		return formItemImpl;
	}

	@Override
	public int compareTo(FormItem formItem) {
		long primaryKey = formItem.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FormItem)) {
			return false;
		}

		FormItem formItem = (FormItem)obj;

		long primaryKey = formItem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FormItemModelImpl formItemModelImpl = this;

		formItemModelImpl._originalFormId = formItemModelImpl._formId;

		formItemModelImpl._setOriginalFormId = false;

		formItemModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FormItem> toCacheModel() {
		FormItemCacheModel formItemCacheModel = new FormItemCacheModel();

		formItemCacheModel.formItemId = getFormItemId();

		formItemCacheModel.active = getActive();

		Date creationDate = getCreationDate();

		if (creationDate != null) {
			formItemCacheModel.creationDate = creationDate.getTime();
		}
		else {
			formItemCacheModel.creationDate = Long.MIN_VALUE;
		}

		Date modificationDate = getModificationDate();

		if (modificationDate != null) {
			formItemCacheModel.modificationDate = modificationDate.getTime();
		}
		else {
			formItemCacheModel.modificationDate = Long.MIN_VALUE;
		}

		formItemCacheModel.modificationUser = getModificationUser();

		String modificationUser = formItemCacheModel.modificationUser;

		if ((modificationUser != null) && (modificationUser.length() == 0)) {
			formItemCacheModel.modificationUser = null;
		}

		formItemCacheModel.formId = getFormId();

		formItemCacheModel.formItemAttrId = getFormItemAttrId();

		String formItemAttrId = formItemCacheModel.formItemAttrId;

		if ((formItemAttrId != null) && (formItemAttrId.length() == 0)) {
			formItemCacheModel.formItemAttrId = null;
		}

		formItemCacheModel.formItemAttrClass = getFormItemAttrClass();

		String formItemAttrClass = formItemCacheModel.formItemAttrClass;

		if ((formItemAttrClass != null) && (formItemAttrClass.length() == 0)) {
			formItemCacheModel.formItemAttrClass = null;
		}

		formItemCacheModel.label = getLabel();

		String label = formItemCacheModel.label;

		if ((label != null) && (label.length() == 0)) {
			formItemCacheModel.label = null;
		}

		formItemCacheModel.labelAttrId = getLabelAttrId();

		String labelAttrId = formItemCacheModel.labelAttrId;

		if ((labelAttrId != null) && (labelAttrId.length() == 0)) {
			formItemCacheModel.labelAttrId = null;
		}

		formItemCacheModel.labelAttrClass = getLabelAttrClass();

		String labelAttrClass = formItemCacheModel.labelAttrClass;

		if ((labelAttrClass != null) && (labelAttrClass.length() == 0)) {
			formItemCacheModel.labelAttrClass = null;
		}

		formItemCacheModel.inputAttrId = getInputAttrId();

		String inputAttrId = formItemCacheModel.inputAttrId;

		if ((inputAttrId != null) && (inputAttrId.length() == 0)) {
			formItemCacheModel.inputAttrId = null;
		}

		formItemCacheModel.inputAttrClass = getInputAttrClass();

		String inputAttrClass = formItemCacheModel.inputAttrClass;

		if ((inputAttrClass != null) && (inputAttrClass.length() == 0)) {
			formItemCacheModel.inputAttrClass = null;
		}

		formItemCacheModel.type = getType();

		String type = formItemCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			formItemCacheModel.type = null;
		}

		formItemCacheModel.optionKeys = getOptionKeys();

		String optionKeys = formItemCacheModel.optionKeys;

		if ((optionKeys != null) && (optionKeys.length() == 0)) {
			formItemCacheModel.optionKeys = null;
		}

		formItemCacheModel.optionValues = getOptionValues();

		String optionValues = formItemCacheModel.optionValues;

		if ((optionValues != null) && (optionValues.length() == 0)) {
			formItemCacheModel.optionValues = null;
		}

		formItemCacheModel.mandatory = getMandatory();

		formItemCacheModel.defaultValue = getDefaultValue();

		String defaultValue = formItemCacheModel.defaultValue;

		if ((defaultValue != null) && (defaultValue.length() == 0)) {
			formItemCacheModel.defaultValue = null;
		}

		formItemCacheModel.order = getOrder();

		formItemCacheModel.validationType = getValidationType();

		String validationType = formItemCacheModel.validationType;

		if ((validationType != null) && (validationType.length() == 0)) {
			formItemCacheModel.validationType = null;
		}

		formItemCacheModel.validationRegexValue = getValidationRegexValue();

		String validationRegexValue = formItemCacheModel.validationRegexValue;

		if ((validationRegexValue != null) &&
				(validationRegexValue.length() == 0)) {
			formItemCacheModel.validationRegexValue = null;
		}

		formItemCacheModel.minLength = getMinLength();

		formItemCacheModel.maxLength = getMaxLength();

		formItemCacheModel.errorValidationMessage = getErrorValidationMessage();

		String errorValidationMessage = formItemCacheModel.errorValidationMessage;

		if ((errorValidationMessage != null) &&
				(errorValidationMessage.length() == 0)) {
			formItemCacheModel.errorValidationMessage = null;
		}

		formItemCacheModel.errorMandatoryMessage = getErrorMandatoryMessage();

		String errorMandatoryMessage = formItemCacheModel.errorMandatoryMessage;

		if ((errorMandatoryMessage != null) &&
				(errorMandatoryMessage.length() == 0)) {
			formItemCacheModel.errorMandatoryMessage = null;
		}

		formItemCacheModel.errorLengthMessage = getErrorLengthMessage();

		String errorLengthMessage = formItemCacheModel.errorLengthMessage;

		if ((errorLengthMessage != null) && (errorLengthMessage.length() == 0)) {
			formItemCacheModel.errorLengthMessage = null;
		}

		formItemCacheModel.hintMessage = getHintMessage();

		String hintMessage = formItemCacheModel.hintMessage;

		if ((hintMessage != null) && (hintMessage.length() == 0)) {
			formItemCacheModel.hintMessage = null;
		}

		return formItemCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(55);

		sb.append("{formItemId=");
		sb.append(getFormItemId());
		sb.append(", active=");
		sb.append(getActive());
		sb.append(", creationDate=");
		sb.append(getCreationDate());
		sb.append(", modificationDate=");
		sb.append(getModificationDate());
		sb.append(", modificationUser=");
		sb.append(getModificationUser());
		sb.append(", formId=");
		sb.append(getFormId());
		sb.append(", formItemAttrId=");
		sb.append(getFormItemAttrId());
		sb.append(", formItemAttrClass=");
		sb.append(getFormItemAttrClass());
		sb.append(", label=");
		sb.append(getLabel());
		sb.append(", labelAttrId=");
		sb.append(getLabelAttrId());
		sb.append(", labelAttrClass=");
		sb.append(getLabelAttrClass());
		sb.append(", inputAttrId=");
		sb.append(getInputAttrId());
		sb.append(", inputAttrClass=");
		sb.append(getInputAttrClass());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", optionKeys=");
		sb.append(getOptionKeys());
		sb.append(", optionValues=");
		sb.append(getOptionValues());
		sb.append(", mandatory=");
		sb.append(getMandatory());
		sb.append(", defaultValue=");
		sb.append(getDefaultValue());
		sb.append(", order=");
		sb.append(getOrder());
		sb.append(", validationType=");
		sb.append(getValidationType());
		sb.append(", validationRegexValue=");
		sb.append(getValidationRegexValue());
		sb.append(", minLength=");
		sb.append(getMinLength());
		sb.append(", maxLength=");
		sb.append(getMaxLength());
		sb.append(", errorValidationMessage=");
		sb.append(getErrorValidationMessage());
		sb.append(", errorMandatoryMessage=");
		sb.append(getErrorMandatoryMessage());
		sb.append(", errorLengthMessage=");
		sb.append(getErrorLengthMessage());
		sb.append(", hintMessage=");
		sb.append(getHintMessage());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(85);

		sb.append("<model><model-name>");
		sb.append("com.rcs.webform.model.FormItem");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>formItemId</column-name><column-value><![CDATA[");
		sb.append(getFormItemId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active</column-name><column-value><![CDATA[");
		sb.append(getActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creationDate</column-name><column-value><![CDATA[");
		sb.append(getCreationDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modificationDate</column-name><column-value><![CDATA[");
		sb.append(getModificationDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modificationUser</column-name><column-value><![CDATA[");
		sb.append(getModificationUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>formId</column-name><column-value><![CDATA[");
		sb.append(getFormId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>formItemAttrId</column-name><column-value><![CDATA[");
		sb.append(getFormItemAttrId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>formItemAttrClass</column-name><column-value><![CDATA[");
		sb.append(getFormItemAttrClass());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>label</column-name><column-value><![CDATA[");
		sb.append(getLabel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>labelAttrId</column-name><column-value><![CDATA[");
		sb.append(getLabelAttrId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>labelAttrClass</column-name><column-value><![CDATA[");
		sb.append(getLabelAttrClass());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inputAttrId</column-name><column-value><![CDATA[");
		sb.append(getInputAttrId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inputAttrClass</column-name><column-value><![CDATA[");
		sb.append(getInputAttrClass());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>optionKeys</column-name><column-value><![CDATA[");
		sb.append(getOptionKeys());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>optionValues</column-name><column-value><![CDATA[");
		sb.append(getOptionValues());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mandatory</column-name><column-value><![CDATA[");
		sb.append(getMandatory());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>defaultValue</column-name><column-value><![CDATA[");
		sb.append(getDefaultValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>order</column-name><column-value><![CDATA[");
		sb.append(getOrder());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>validationType</column-name><column-value><![CDATA[");
		sb.append(getValidationType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>validationRegexValue</column-name><column-value><![CDATA[");
		sb.append(getValidationRegexValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>minLength</column-name><column-value><![CDATA[");
		sb.append(getMinLength());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maxLength</column-name><column-value><![CDATA[");
		sb.append(getMaxLength());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>errorValidationMessage</column-name><column-value><![CDATA[");
		sb.append(getErrorValidationMessage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>errorMandatoryMessage</column-name><column-value><![CDATA[");
		sb.append(getErrorMandatoryMessage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>errorLengthMessage</column-name><column-value><![CDATA[");
		sb.append(getErrorLengthMessage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hintMessage</column-name><column-value><![CDATA[");
		sb.append(getHintMessage());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FormItem.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FormItem.class
		};
	private long _formItemId;
	private boolean _active;
	private Date _creationDate;
	private Date _modificationDate;
	private String _modificationUser;
	private long _formId;
	private long _originalFormId;
	private boolean _setOriginalFormId;
	private String _formItemAttrId;
	private String _formItemAttrClass;
	private String _label;
	private String _labelCurrentLanguageId;
	private String _labelAttrId;
	private String _labelAttrClass;
	private String _inputAttrId;
	private String _inputAttrClass;
	private String _type;
	private String _optionKeys;
	private String _optionValues;
	private String _optionValuesCurrentLanguageId;
	private boolean _mandatory;
	private String _defaultValue;
	private String _defaultValueCurrentLanguageId;
	private int _order;
	private String _validationType;
	private String _validationRegexValue;
	private int _minLength;
	private int _maxLength;
	private String _errorValidationMessage;
	private String _errorValidationMessageCurrentLanguageId;
	private String _errorMandatoryMessage;
	private String _errorMandatoryMessageCurrentLanguageId;
	private String _errorLengthMessage;
	private String _errorLengthMessageCurrentLanguageId;
	private String _hintMessage;
	private String _hintMessageCurrentLanguageId;
	private long _columnBitmask;
	private FormItem _escapedModel;
}